### Install basic system packages
- name: Install basic packages
  apt: 
    pkg:
      - vim
      - curl
      - wget
      - zip
      - unzip
      - git
    state: present

### Convenience
- name: Configure inputrc / vimrc and motd for root
  become: yes
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
   - { src: inputrc, dest: /root/.inputrc }
   - { src: vimrc, dest: /root/.vimrc }
   - { src: bashrc, dest: /root/.bashrc }
   - { src: aliases, dest: /root/.bash_aliases }
   - { src: inputrc, dest: /home/vagrant/.inputrc }
   - { src: vimrc, dest: /home/vagrant/.vimrc }
   - { src: motd, dest: /etc/motd }
   - { src: bashrc, dest: /home/vagrant/.bashrc }
   - { src: aliases, dest: /home/vagrant/.bash_aliases }

- name: Others configs
  lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line }}"
  with_items:
    - { path: '/etc/sysctl.conf', line: "vm.overcommit_memory={{ over_commit_memory }}" }
    - { path: '/etc/systemd/journald.conf', line: "SystemMaxUse=100M" }

- name: remove old motd
  file:
    path: /etc/update-motd.d/
    state: absent
  become: yes

# final clean
- name: Remove dependencies that are no longer required
  apt:
      autoremove: yes
      purge: yes
      force: yes
      update_cache: true
  become: yes
  tags:
      - system

- name: Clean up apt.
  command: "{{ item }}"
  changed_when: false
  with_items:
      - apt-get -y autoremove
      - apt-get -y clean

